DROP USER arss CASCADE;

CREATE USER arss IDENTIFIED BY "5eagateFinanace";

GRANT
    CREATE USER,
    ALTER USER,
    DROP USER,
    CREATE PROFILE
TO arss WITH ADMIN OPTION;

GRANT connect TO arss WITH ADMIN OPTION;

GRANT resource TO arss WITH ADMIN OPTION;

GRANT
    CREATE SEQUENCE,
    CREATE OPERATOR,
    CREATE SESSION,
    ALTER SESSION,
    CREATE PROCEDURE,
    CREATE VIEW,
    CREATE JOB,
    CREATE DIMENSION,
    CREATE INDEXTYPE,
    CREATE TYPE,
    CREATE TRIGGER,
    CREATE TABLE,
    CREATE PROFILE
TO arss WITH ADMIN OPTION;

GRANT
    UNLIMITED TABLESPACE
TO arss WITH ADMIN OPTION;

GRANT SELECT ON sys.dba_profiles TO arss WITH GRANT OPTION;

GRANT SELECT ON sys.dba_users TO arss WITH GRANT OPTION;

GRANT SELECT ON sys.dba_data_files TO arss WITH GRANT OPTION;

GRANT SELECT ON sys.dba_segments TO arss WITH GRANT OPTION;