DROP TABLE vb_vb_istvpkfgk4j.xxgstt_arss_inv_req_dist_int;

CREATE TABLE vb_vb_istvpkfgk4j.xxgstt_arss_inv_req_dist_int (
    oic_flow_id                  NUMBER(15,0),
    arss_invoice_reference       VARCHAR2(30 BYTE),
    arss_invoice_id              NUMBER(15,0),
    arss_invoice_line_id         NUMBER(15,0),
    arss_invoice_dist_id         NUMBER(15,0),
	fbdi_string                  VARCHAR2(10000 BYTE),
    interface_distribution_id    NUMBER(15,0),
    interface_line_id            NUMBER(15,0),
    interface_line_context       VARCHAR2(30 BYTE),
    interface_line_attribute1    VARCHAR2(150 BYTE),
    interface_line_attribute2    VARCHAR2(150 BYTE),
    interface_line_attribute3    VARCHAR2(150 BYTE),
    interface_line_attribute4    VARCHAR2(150 BYTE),
    interface_line_attribute5    VARCHAR2(150 BYTE),
    interface_line_attribute6    VARCHAR2(150 BYTE),
    interface_line_attribute7    VARCHAR2(150 BYTE),
    interface_line_attribute8    VARCHAR2(150 BYTE),
    account_class                VARCHAR2(20 BYTE)
        NOT NULL ENABLE,
    amount                       NUMBER,
    percent                      NUMBER,
    interface_status             VARCHAR2(1 BYTE),
    request_id                   NUMBER(15,0),
    code_combination_id          NUMBER(15,0),
    segment1                     VARCHAR2(25 BYTE),
    segment2                     VARCHAR2(25 BYTE),
    segment3                     VARCHAR2(25 BYTE),
    segment4                     VARCHAR2(25 BYTE),
    segment5                     VARCHAR2(25 BYTE),
    segment6                     VARCHAR2(25 BYTE),
    segment7                     VARCHAR2(25 BYTE),
    segment8                     VARCHAR2(25 BYTE),
    segment9                     VARCHAR2(25 BYTE),
    segment10                    VARCHAR2(25 BYTE),
    segment11                    VARCHAR2(25 BYTE),
    segment12                    VARCHAR2(25 BYTE),
    segment13                    VARCHAR2(25 BYTE),
    segment14                    VARCHAR2(25 BYTE),
    segment15                    VARCHAR2(25 BYTE),
    segment16                    VARCHAR2(25 BYTE),
    segment17                    VARCHAR2(25 BYTE),
    segment18                    VARCHAR2(25 BYTE),
    segment19                    VARCHAR2(25 BYTE),
    segment20                    VARCHAR2(25 BYTE),
    segment21                    VARCHAR2(25 BYTE),
    segment22                    VARCHAR2(25 BYTE),
    segment23                    VARCHAR2(25 BYTE),
    segment24                    VARCHAR2(25 BYTE),
    segment25                    VARCHAR2(25 BYTE),
    segment26                    VARCHAR2(25 BYTE),
    segment27                    VARCHAR2(25 BYTE),
    segment28                    VARCHAR2(25 BYTE),
    segment29                    VARCHAR2(25 BYTE),
    segment30                    VARCHAR2(25 BYTE),
    comments                     VARCHAR2(240 BYTE),
    attribute_category           VARCHAR2(30 BYTE),
    attribute1                   VARCHAR2(150 BYTE),
    attribute2                   VARCHAR2(150 BYTE),
    attribute3                   VARCHAR2(150 BYTE),
    attribute4                   VARCHAR2(150 BYTE),
    attribute5                   VARCHAR2(150 BYTE),
    attribute6                   VARCHAR2(150 BYTE),
    attribute7                   VARCHAR2(150 BYTE),
    attribute8                   VARCHAR2(150 BYTE),
    attribute9                   VARCHAR2(150 BYTE),
    attribute10                  VARCHAR2(150 BYTE),
    attribute11                  VARCHAR2(150 BYTE),
    attribute12                  VARCHAR2(150 BYTE),
    attribute13                  VARCHAR2(150 BYTE),
    attribute14                  VARCHAR2(150 BYTE),
    attribute15                  VARCHAR2(150 BYTE),
    acctd_amount                 NUMBER,
    interface_line_attribute10   VARCHAR2(150 BYTE),
    interface_line_attribute11   VARCHAR2(150 BYTE),
    interface_line_attribute12   VARCHAR2(150 BYTE),
    interface_line_attribute13   VARCHAR2(150 BYTE),
    interface_line_attribute14   VARCHAR2(150 BYTE),
    interface_line_attribute15   VARCHAR2(150 BYTE),
    interface_line_attribute9    VARCHAR2(150 BYTE),
    created_by                   NUMBER(15,0),
    creation_date                DATE,
    last_updated_by              NUMBER(15,0),
    last_update_date             DATE,
    last_update_login            NUMBER(15,0),
    org_id                       NUMBER(15,0) DEFAULT NULL,
    interim_tax_ccid             NUMBER(15,0),
    interim_tax_segment1         VARCHAR2(25 BYTE),
    interim_tax_segment2         VARCHAR2(25 BYTE),
    interim_tax_segment3         VARCHAR2(25 BYTE),
    interim_tax_segment4         VARCHAR2(25 BYTE),
    interim_tax_segment5         VARCHAR2(25 BYTE),
    interim_tax_segment6         VARCHAR2(25 BYTE),
    interim_tax_segment7         VARCHAR2(25 BYTE),
    interim_tax_segment8         VARCHAR2(25 BYTE),
    interim_tax_segment9         VARCHAR2(25 BYTE),
    interim_tax_segment10        VARCHAR2(25 BYTE),
    interim_tax_segment11        VARCHAR2(25 BYTE),
    interim_tax_segment12        VARCHAR2(25 BYTE),
    interim_tax_segment13        VARCHAR2(25 BYTE),
    interim_tax_segment14        VARCHAR2(25 BYTE),
    interim_tax_segment15        VARCHAR2(25 BYTE),
    interim_tax_segment16        VARCHAR2(25 BYTE),
    interim_tax_segment17        VARCHAR2(25 BYTE),
    interim_tax_segment18        VARCHAR2(25 BYTE),
    interim_tax_segment19        VARCHAR2(25 BYTE),
    interim_tax_segment20        VARCHAR2(25 BYTE),
    interim_tax_segment21        VARCHAR2(25 BYTE),
    interim_tax_segment22        VARCHAR2(25 BYTE),
    interim_tax_segment23        VARCHAR2(25 BYTE),
    interim_tax_segment24        VARCHAR2(25 BYTE),
    interim_tax_segment25        VARCHAR2(25 BYTE),
    interim_tax_segment26        VARCHAR2(25 BYTE),
    interim_tax_segment27        VARCHAR2(25 BYTE),
    interim_tax_segment28        VARCHAR2(25 BYTE),
    interim_tax_segment29        VARCHAR2(25 BYTE),
    interim_tax_segment30        VARCHAR2(25 BYTE)
);

/

SHOW ERR;